github sha on merge for develop repo
SecureBankingAccessToolkit/securebanking-openbanking-demo pull request #62
Opened 2021-09-24 14:13 UTC by jterryfr

Create github sha in the develop repo.

issue:  https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/89

2021-09-24 14:21 UTC, BohoCode approved these changes

2021-09-24 14:25 UTC, jorgesanchezperez reviewed
some comments added.

2021-09-24 14:25 UTC, jorgesanchezperez commented on .github/workflows/merge.yml
> +          make build-docker-ig tag=${{ github.sha }}
This will build only Ig, that's correct?

2021-09-24 14:25 UTC, jorgesanchezperez commented on .github/workflows/merge.yml
> +          make build-docker-ig tag=${{ github.sha }}
It won't be better something like below in the make file:
`docker build docker/7.0/ig/ -t eu.gcr.io/${gcr-repo}/securebanking/gate/ig:latest -t eu.gcr.io/${gcr-repo}/securebanking/gate/ig:${tag}`
and
`docker push ....`

And call the make file only once `make build-docker-ig tag=xxx gcr-repo=xxx`

2021-09-27 07:28 UTC, jorgesanchezperez commented on .github/workflows/merge.yml
> +          docker push eu.gcr.io/${{ secrets.RELEASE_REPO}}:latest
Must be the same repository to have the same image tagged with latest and github.sha.
- docker push eu.gcr.io/${REPO}:latest
- docker push eu.gcr.io/${REPO}:{{ github.sha }}

2021-09-27 14:06 UTC, jorgesanchezperez requested changes

2021-09-27 14:07 UTC, jterryfr commented on .github/workflows/merge.yml
> +          docker push eu.gcr.io/${{ secrets.DEV_REPO }}:latest
the initial `make build-docker-ig tag=${{ github.sha }}` already does that

2021-09-27 14:39 UTC, jorgesanchezperez approved these changes

2021-09-27 14:41 UTC, merged